# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-17 15:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0002_auto_20170817_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bean',
            name='price',
            field=models.DecimalField(decimal_places=3, max_digits=7),
        ),
        migrations.AlterField(
            model_name='powder',
            name='price',
            field=models.DecimalField(decimal_places=3, max_digits=7),
        ),
        migrations.AlterField(
            model_name='roast',
            name='price',
            field=models.DecimalField(decimal_places=3, max_digits=7),
        ),
        migrations.AlterField(
            model_name='syrup',
            name='price',
            field=models.DecimalField(decimal_places=3, max_digits=7),
        ),
    ]
